using OzzContextGen.Core.Models;
using OzzContextGen.i18n;
using System.Text;

namespace OzzContextGen.Core;

/// <summary>
/// The PackerEngine class is responsible for generating a markdown string that contains the source code of a project. It scans the specified source directory for code files, reads their content, and formats them into a structured markdown format suitable for LLM context generation. The class also provides progress reporting through an optional callback action.
/// </summary>
public class PackerEngine
{

    /// <summary>
    /// Generates a markdown string containing the source code of the project located at <paramref name="sourcePath"/>.
    /// </summary>
    /// <param name="sourcePath">The root folder path of the project</param>
    /// <param name="progressAction">A callback to report progress to the UI (optional)</param>
    public async Task<string> PackSourceCodeAsync(string sourcePath, Action<string>? progressAction = null)
    {
        if (!Directory.Exists(sourcePath))
        {
            throw new DirectoryNotFoundException(string.Format(LocalizedStrings.SourceFolderNotFound, sourcePath));
        }

        progressAction?.Invoke(LocalizedStrings.ScanningFiles);

        var codeCrawler = new CodeCrawler(SourceLanguages.All.Keys.ToArray());
        var codeFiles = codeCrawler.GetCodeFiles(sourcePath).Select(f => new FileContextEntry() { RelativePath = Path.GetRelativePath(sourcePath, f) }).ToList();

        return await PackSourceCodeAsync(codeFiles, sourcePath, progressAction);
    }

    public static async Task<string> PackSourceCodeAsync(List<FileContextEntry> codeFiles, string sourcePath, Action<string>? progressAction)
    {
        progressAction?.Invoke(string.Format(LocalizedStrings.FoundFiles, codeFiles.Count));

        var sb = new StringBuilder();

        // Add a system prompt at the beginning of the Markdown file to guide the AI
        sb.AppendLine("# LLM CONTEXT - PROJECT SOURCE CODE PACK");
        sb.AppendLine($"*Generated by OzzContextGen on {DateTime.Now:yyyy-MM-dd HH:mm:ss}*");
        sb.AppendLine($"*Total Files:* {codeFiles.Count}");
        sb.AppendLine("---");
        sb.AppendLine("Below is the structural source code of the project. Each file is separated by a markdown header and enclosed in code blocks.");
        sb.AppendLine();

        foreach (var file in codeFiles)
        {
            // Notify the user which file is being processed via GUI or CLI
            string relativePath = file.RelativePath;
            progressAction?.Invoke(string.Format(LocalizedStrings.ProcessingFile, relativePath));
            if (file.PackingMode == PackingMode.Excluded)
                continue; // Skip excluded files


            sb.AppendLine($"## FILE: {relativePath}");

            if (!string.IsNullOrWhiteSpace(file.ContextNote))
            {
                sb.AppendLine($"**Note:** {file.ContextNote}");
            }

            if (file.PackingMode == PackingMode.MetadataOnly)
            {
                if (string.IsNullOrWhiteSpace(file.ContextNote))
                {
                    sb.AppendLine($"**Packing Mode:** Metadata Only");
                    sb.AppendLine();
                }
                continue; // Skip reading the file content
            }


            string fullPath = Path.Combine(sourcePath, relativePath);
            if (!File.Exists(fullPath))
            {
                sb.AppendLine($"**ERROR:** File not found at path: {relativePath}");
                sb.AppendLine();
                continue;
            }

            string suffix = Path.GetExtension(relativePath);
            string fence = SourceLanguages.TryGet(suffix)?.MarkdownFence ?? "text";

            try
            {
                // Read the file asynchronously to prevent UI blocking in large projects
                string content = await File.ReadAllTextAsync(fullPath, Encoding.UTF8);

                // Exceptions likely to be thrown during files are being read, so we put fence after reading the file
                sb.AppendLine($"```{fence}");
                sb.AppendLine(content.TrimEnd('\r', '\n'));
                sb.AppendLine("```");
            }
            catch (Exception ex)
            {
                sb.AppendLine();
                sb.AppendLine($"**ERROR While Reading File:** {ex.Message}");
                if (ex.InnerException != null)
                    sb.AppendLine(ex.InnerException.Message);

                sb.AppendLine();
            }

            sb.AppendLine(); // Add a blank line between files
        }

        progressAction?.Invoke(LocalizedStrings.PackagingCompleted);
        return sb.ToString();
    }
}
