using OzzContextGen.i18n;
using System.Text;

namespace OzzContextGen.Core
{
    public class PackerEngine
    {

        /// <summary>
        /// Belirtilen kaynak klasördeki C# dosyalarını tarar ve tek bir Markdown metni üretir.
        /// </summary>
        /// <param name="sourcePath">Projenin kök klasör yolu</param>
        /// <param name="progressAction">Arayüz (GUI) için ilerleme durumunu bildiren callback (isteğe bağlı)</param>
        public async Task<string> PackSourceCodeAsync(string sourcePath, Action<string>? progressAction = null)
        {
            if (!Directory.Exists(sourcePath))
            {
                throw new DirectoryNotFoundException(string.Format(LocalizedStrings.SourceFolderNotFound, sourcePath));
            }

            progressAction?.Invoke(LocalizedStrings.ScanningFiles);

            var codeCrawler = new CodeCrawler(".cs");
            var codeFiles = codeCrawler.GetCodeFiles(sourcePath).ToList();

            return await PackSourceCodeAsync(codeFiles, sourcePath, progressAction);
        }

        public static async Task<string> PackSourceCodeAsync(List<string> codeFiles, string sourcePath, Action<string>? progressAction)
        {
            progressAction?.Invoke(string.Format(LocalizedStrings.FoundFiles, codeFiles.Count));

            var sb = new StringBuilder();

            // Markdown dosyasının en başına yapay zekaya rehberlik edecek bir sistem promptu ekliyoruz
            sb.AppendLine("# LLM CONTEXT - PROJECT SOURCE CODE PACK");
            sb.AppendLine($"*Generated by OzzContextGen on {DateTime.Now:yyyy-MM-dd HH:mm:ss}*");
            sb.AppendLine($"*Total Files:* {codeFiles.Count}");
            sb.AppendLine("---");
            sb.AppendLine("Below is the structural source code of the project. Each file is separated by a markdown header and enclosed in code blocks.");
            sb.AppendLine();

            foreach (var filePath in codeFiles)
            {
                // Kullanıcıya hangi dosyanın işlendiğini GUI veya CLI üzerinden bildiriyoruz
                string relativePath = Path.GetRelativePath(sourcePath, filePath);
                progressAction?.Invoke(string.Format(LocalizedStrings.ProcessingFile, relativePath));

                sb.AppendLine($"## FILE: {relativePath}");
                sb.AppendLine("```csharp");

                try
                {
                    // Büyük projelerde UI kilitlenmesini önlemek için asenkron okuma yapıyoruz
                    string content = await File.ReadAllTextAsync(filePath, Encoding.UTF8);
                    sb.AppendLine(content);
                }
                catch (Exception ex)
                {
                    sb.AppendLine($"// ERROR: File could not be read. {ex.Message}");
                }

                sb.AppendLine("```");
                sb.AppendLine(); // Dosyalar arasında boşluk bırakıyoruz
            }

            progressAction?.Invoke(LocalizedStrings.PackagingCompleted);
            return sb.ToString();
        }
    }
}
