using OzzContextGen.Core.Models;
using OzzContextGen.i18n;
using System.Text;

namespace OzzContextGen.Core
{
    public class PackerEngine
    {

        /// <summary>
        /// Generates a markdown string containing the source code of the project located at <paramref name="sourcePath"/>.
        /// </summary>
        /// <param name="sourcePath">The root folder path of the project</param>
        /// <param name="progressAction">A callback to report progress to the UI (optional)</param>
        public async Task<string> PackSourceCodeAsync(string sourcePath, Action<string>? progressAction = null)
        {
            if (!Directory.Exists(sourcePath))
            {
                throw new DirectoryNotFoundException(string.Format(LocalizedStrings.SourceFolderNotFound, sourcePath));
            }

            progressAction?.Invoke(LocalizedStrings.ScanningFiles);

            var codeCrawler = new CodeCrawler(SourceLanguages.All.Keys.ToArray());
            var codeFiles = codeCrawler.GetCodeFiles(sourcePath).Select(f => new FileContextEntry() { RelativePath = Path.GetRelativePath(sourcePath, f) }).ToList();

            return await PackSourceCodeAsync(codeFiles, sourcePath, progressAction);
        }

        public static async Task<string> PackSourceCodeAsync(List<FileContextEntry> codeFiles, string sourcePath, Action<string>? progressAction)
        {
            progressAction?.Invoke(string.Format(LocalizedStrings.FoundFiles, codeFiles.Count));

            var sb = new StringBuilder();

            // Add a system prompt at the beginning of the Markdown file to guide the AI
            sb.AppendLine("# LLM CONTEXT - PROJECT SOURCE CODE PACK");
            sb.AppendLine($"*Generated by OzzContextGen on {DateTime.Now:yyyy-MM-dd HH:mm:ss}*");
            sb.AppendLine($"*Total Files:* {codeFiles.Count}");
            sb.AppendLine("---");
            sb.AppendLine("Below is the structural source code of the project. Each file is separated by a markdown header and enclosed in code blocks.");
            sb.AppendLine();

            foreach (var filePath in codeFiles)
            {
                // Notify the user which file is being processed via GUI or CLI
                string relativePath = filePath.RelativePath;
                progressAction?.Invoke(string.Format(LocalizedStrings.ProcessingFile, relativePath));

                string suffix = Path.GetExtension(relativePath);
                string fence = SourceLanguages.TryGet(suffix)?.MarkdownFence ?? "text";

                sb.AppendLine($"## FILE: {relativePath}");
                sb.AppendLine($"```{fence}");

                try
                {
                    // Read the file asynchronously to prevent UI blocking in large projects
                    string content = await File.ReadAllTextAsync(Path.Combine(sourcePath, filePath.RelativePath), Encoding.UTF8);
                    sb.AppendLine(content);
                }
                catch (Exception ex)
                {
                    sb.AppendLine($"// ERROR: File could not be read. {ex.Message}");
                }

                sb.AppendLine("```");
                sb.AppendLine(); // Add a blank line between files
            }

            progressAction?.Invoke(LocalizedStrings.PackagingCompleted);
            return sb.ToString();
        }
    }
}
