//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzzContextGen.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OzzContextGen.i18n.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Changes.
        /// </summary>
        public static string AnalyzeChanges {
            get {
                return ResourceManager.GetString("AnalyzeChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully completed Packing and Profile update.
        /// </summary>
        public static string CompletedProfilePacking {
            get {
                return ResourceManager.GetString("CompletedProfilePacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path of the Context State Profile file.
        /// </summary>
        public static string ConfigDescription {
            get {
                return ResourceManager.GetString("ConfigDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Note.
        /// </summary>
        public static string ContextNote {
            get {
                return ResourceManager.GetString("ContextNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example Usage (Task Scheduler or Terminal).
        /// </summary>
        public static string ExampleUsage {
            get {
                return ResourceManager.GetString("ExampleUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded.
        /// </summary>
        public static string Excluded {
            get {
                return ResourceManager.GetString("Excluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total found C# files, {0}. Starting to package....
        /// </summary>
        public static string FoundFiles {
            get {
                return ResourceManager.GetString("FoundFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Pack.
        /// </summary>
        public static string FullPack {
            get {
                return ResourceManager.GetString("FullPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Markdown file.
        /// </summary>
        public static string GeneratingMarkdown {
            get {
                return ResourceManager.GetString("GeneratingMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays this help information.
        /// </summary>
        public static string HelpDescription {
            get {
                return ResourceManager.GetString("HelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OzzContextGen - An Intelligent Code Packing and Context Tool for LLMs.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Select a valid source folder.
        /// </summary>
        public static string InvalidSourceFolder {
            get {
                return ResourceManager.GetString("InvalidSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown File (*.md)|*.md.
        /// </summary>
        public static string MarkdownFileFilter {
            get {
                return ResourceManager.GetString("MarkdownFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Only.
        /// </summary>
        public static string MetadataOnly {
            get {
                return ResourceManager.GetString("MetadataOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter.
        /// </summary>
        public static string MissingParameter {
            get {
                return ResourceManager.GetString("MissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No files selected for packing.
        /// </summary>
        public static string NoFilesSelectedForPacking {
            get {
                return ResourceManager.GetString("NoFilesSelectedForPacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Context State Profile tracking and packs everything from scratch.
        /// </summary>
        public static string NoHistoryDescription {
            get {
                return ResourceManager.GetString("NoHistoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open/Create....
        /// </summary>
        public static string OpenCreate {
            get {
                return ResourceManager.GetString("OpenCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an OzzContext Profile (.ctxgen).
        /// </summary>
        public static string OpenProfile {
            get {
                return ResourceManager.GetString("OpenProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully.
        /// </summary>
        public static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Parameters.
        /// </summary>
        public static string OptionalParameters {
            get {
                return ResourceManager.GetString("OptionalParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path of the Markdown file to be generated.
        /// </summary>
        public static string OutputDescription {
            get {
                return ResourceManager.GetString("OutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output (.md):.
        /// </summary>
        public static string OutputFile {
            get {
                return ResourceManager.GetString("OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        public static string Pack {
            get {
                return ResourceManager.GetString("Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging process completed successfully..
        /// </summary>
        public static string PackagingCompleted {
            get {
                return ResourceManager.GetString("PackagingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Context (generate .md).
        /// </summary>
        public static string PackContext {
            get {
                return ResourceManager.GetString("PackContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Error.
        /// </summary>
        public static string ParameterError {
            get {
                return ResourceManager.GetString("ParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing: {0}.
        /// </summary>
        public static string ProcessingFile {
            get {
                return ResourceManager.GetString("ProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile (.ctxgen):.
        /// </summary>
        public static string ProfileFile {
            get {
                return ResourceManager.GetString("ProfileFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OzzContext Profile (*.ctxgen)|*.ctxgen.
        /// </summary>
        public static string ProfileFileFilter {
            get {
                return ResourceManager.GetString("ProfileFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove deleted files from list.
        /// </summary>
        public static string RemoveDeletedFiles {
            get {
                return ResourceManager.GetString("RemoveDeletedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Parameters.
        /// </summary>
        public static string RequiredParameters {
            get {
                return ResourceManager.GetString("RequiredParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving profile state.
        /// </summary>
        public static string SavingProfile {
            get {
                return ResourceManager.GetString("SavingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning folder and analyzing changes.
        /// </summary>
        public static string ScanningAnalyzingChanges {
            get {
                return ResourceManager.GetString("ScanningAnalyzingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning file list....
        /// </summary>
        public static string ScanningFiles {
            get {
                return ResourceManager.GetString("ScanningFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning is finished. Listed {0} files.
        /// </summary>
        public static string ScanningFinished {
            get {
                return ResourceManager.GetString("ScanningFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning source folder.
        /// </summary>
        public static string ScanningSource {
            get {
                return ResourceManager.GetString("ScanningSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Target....
        /// </summary>
        public static string SelectTarget {
            get {
                return ResourceManager.GetString("SelectTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root folder path of the project&apos;s source code.
        /// </summary>
        public static string SourceDescription {
            get {
                return ResourceManager.GetString("SourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Folder:.
        /// </summary>
        public static string SourceFolder {
            get {
                return ResourceManager.GetString("SourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source folder not found: {0}.
        /// </summary>
        public static string SourceFolderNotFound {
            get {
                return ResourceManager.GetString("SourceFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please specify output path.
        /// </summary>
        public static string SpecifyOutputPath {
            get {
                return ResourceManager.GetString("SpecifyOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting OzzContextGen....
        /// </summary>
        public static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting packing process.
        /// </summary>
        public static string StartingPackingProcess {
            get {
                return ResourceManager.GetString("StartingPackingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error Occured.
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchanged.
        /// </summary>
        public static string Unchanged {
            get {
                return ResourceManager.GetString("Unchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parameter.
        /// </summary>
        public static string UnknownParameter {
            get {
                return ResourceManager.GetString("UnknownParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OzzContextGen -s &lt;source_folder&gt; -o &lt;output_file_path&gt; [options].
        /// </summary>
        public static string UsageExample01 {
            get {
                return ResourceManager.GetString("UsageExample01", resourceCulture);
            }
        }
    }
}
